name: Docker Build Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 16 * * *'

permissions:
  id-token: write
  contents: read
  packages: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Dockerfile
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        context: .
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/sbom-test:latest
        load: true

    - name: Scan Dockerfile for vulnerabilities
      uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32
      id: scan
      with:
        image: "ghcr.io/${{ github.repository_owner }}/sbom-test:latest"
        fail-build: true

    - name: upload SARIF report
      uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Push Dockerfile
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/sbom-test:latest
